name: Run pre-commmit hooks

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  success:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: |
        exit 0
  # fail:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Run
  #     run: |
  #       exit 1
